name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 12
    - run: npm i
    - run: npx playwright install-deps
    - run: npm run build
    - run: npm run lint
    - name: Tests
      if: matrix.os == 'ubuntu-latest'
      run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- bash -c "npm run test"
    - name: Tests
      if: matrix.os != 'ubuntu-latest'
      run: npm run test
